use_frameworks!

platform :ios, '9.0'

target 'SWNetwork_Example' do
  pod 'SWNetwork', :path => '../'
  pod 'MBProgressHUD', '~> 1.2.0'

  target 'SWNetwork_Tests' do
    inherit! :search_paths

    
  end
end
